# sudo python3 installer.py
import os, time, sys

os.system('clear')
os.system('sudo apt update -y && sudo apt upgrade -y') 
os.system('sudo apt install nodejs -y')
os.system('sudo apt install npm -y')
os.system('sudo apt install python3 -y')
os.system('sudo apt install python3-pip -y')
os.system('npm i hpack')
os.system('npm i colors')
os.system('npm i user-agents')
os.system('npm i axios header-generator random-useragent readline-sync') 
os.system('npm i node-fetch')
os.system('wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash')
os.system('source ~/.bashrc')
os.system('nvm install 20')
os.system('nvm use 20')
os.system('npm i gradient-string')
os.system('pip install node-fetch') 
os.system('npm i sockopt') 
os.system('npm i cheerio')
os.system('pip install colorama request')
time.sleep(1)
os.system('clear')
time.sleep(5)
sys.exit()